---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Peer Reviewed

<br>
<ol reversed>
<li>Koga, N. M., Loureiro, M., Palotti, P. L. de M., <u>**Lins, R. da S.**</u>,  Couto, B. G. do, Lima, S. N. "Beyond Evidence-Based Policy: Information sources bureaucrats in the Global South
use in policymaking", **Policy & Politics** (conditionally accepted).</li>
<br>
<li>Palotti, P. L. de M., Koga, N. M., Couto, B. G. do, Nascimento, M. I. B. do e <u>**Lins, R. da S.**</u> (2021). "Uso de evidência pela burocracia dirigente do nível Federal". **Instituto de Pesquisa Econômica Aplicada (Ipea)**, Brasília (Publicação Preliminar).<br>[ <a href="http://repositorio.ipea.gov.br/bitstream/11058/10966/1/pub_preliminar_td_uso_de_evidencias_pela_burocracia.pdf" style = "font-family:Palatino, Garamond, Times, serif; font-variant: small-caps;color:#337ab7;text-decoration: none; font-size:17px">journal</a> ]</li>
<br>
<li>Koga, N. M., Palotti, P. L. de M., Couto, B. G. do, <u>**Lins, R. da S.**</u> and Nascimento, M. I. B. do (2021) "The use of multiple sources of information in public policy: the Brazilian federal bureaucracy", **Revista de Administração Pública**. Rio de Janeiro, RJ, 55(5), p. 1165–1190.<br>[ <a href="https://bibliotecadigital.fgv.br/ojs/index.php/rap/article/view/84860/80298" style = "font-family:Palatino, Garamond, Times, serif; font-variant: small-caps;color:#337ab7;text-decoration: none; font-size:17px">journal</a> ]</li>
<br>
<li>Koga, N. M., Palotti, P. L., <u>**Lins, R. da S.**</u> e Goellner, I. (2021). "Dez Anos de Produção Diest: um levantamento das agendas temáticas na análise de políticas públicas". **Boletim de Análise Político-Institucional**. 29-40.<br>[ <a href="http://repositorio.ipea.gov.br/bitstream/11058/10633/1/bapi_29_dez_anos_producao.pdf" style = "font-family:Palatino, Garamond, Times, serif; font-variant: small-caps;color:#337ab7;text-decoration: none; font-size:17px">journal</a> ]</li>
<br>
<li>Gomide, A. de A., <u>**Lins, R. da S.**</u> e Machado, R. A. (2021). "Burocracia e desempenho da administração pública: Em busca de teorias e evidências para reformas administrativas em países em desenvolvimento". **Cadernos Gestão Pública e Cidadania**, São Paulo. v26. 1-21.<br>[ <a href="https://bibliotecadigital.fgv.br/ojs/index.php/cgpc/article/view/83067/79450" style = "font-family:Palatino, Garamond, Times, serif; font-variant: small-caps;color:#337ab7;text-decoration: none; font-size:17px">journal</a> ]</li>
<br>
<li>Koga, N. M., Palotti, P. L. de M., Couto, B. G. do, Nascimento, M. I. B. do e <u>**Lins, R. da S.**</u> (2020). "O que informa as políticas públicas: *Survey* sobre o uso e o não uso de evidências pela Burocracia Federal Brasileira". **Instituto de Pesquisa Econômica Aplicada (Ipea)**, Brasília (Texto para Discussão, n. 2619).<br>[ <a href="https://www.ipea.gov.br/portal/images/stories/PDFs/TDs/201217_td_2619_web.pdf" style = "font-family:Palatino, Garamond, Times, serif; font-variant: small-caps;color:#337ab7;text-decoration: none; font-size:17px">journal</a> ]</li>

</ol>




